Languages 💬:
  - Fortran
  - C++
  - C/C++
  - Julia
  - Python

Parallelism 🔀:
  - Parallelism
  - OpenMP
  - MPI

GPU 🎮:
  - GPU
  - OpenMP offload
  - OpenACC
  - CUDA
  - HIP

Performance 📊:
  - Performance Engineering
  - Performance Analysis
  - Tools

Development Skills 🪒:
  - UNIX
  - Git
  - Containers


Other 📦:
  - Professional Skills
  - Other

Community 🎉:
  - Seminar
  - Community