Languages 💬:
  - Fortran
  - C++
  - C/C++
  - Julia
  - Python

Parallelism 🔀:
  - Parallelism
  - OpenMP
  - MPI

GPU 🎮:
  - GPU
  - OpenMP offload
  - OpenACC
  - CUDA
  - HIP

Performance 📊:
  - Performance Engineering
  - Performance Analysis
  - Tools

Other 📦:
  - Containers
  - Professional Skills

Community 🎉:
  - Seminar
  - Community